### ISSUE TITLE
Syrcus Tower Required Plugins Missing & Discord Link Broken

### ISSUE THREAD

**Issue by GallJ93** [domesticwarlord86/RebornProfiles#1]
Hello,

Your profiles are looking like they're going to be extremely useful, so thanks for the effort.

I noticed that the Syrcus Tower profile requires 2 plugins: "Osiris" and "SycrusAssist". Neither of these have any instructions for installation and are not included in the repo, plus the Sycrus should be Syrcus.

I also noted that the Discord link was broken, as I was hoping to join.

**Comment by DomesticWarlord** [comment]
Here's you a new discord link https://discord.gg/aFZRBhAYPJ

Feel free to message me over on discord about the Syrcus profile. It's not something that's really ready for the public but I'm to talk about it with you.

**Comment by GallJ93** [comment]
Thanks for the help! Issue is resolved.
