### ISSUE TITLE
Zadnor locks onto irrelevant mobs

### ISSUE THREAD

**Issue by rrbailey89** [domesticwarlord86/RebornProfiles#38]
When going from fate to fate the profile may aggro mobs, when it reaches its destination instead of locking on and attacking the fate relevant mobs it will try and kill the aggro mob it picked up enroute. This normally wouldnt be an issue, but if the area is packed with people then the fate is completed before the bot can even tag it because it wasted time killing the aggro.

**Comment by DomesticWarlord** [comment]
Unfortunately this is a limitation of OrderBot. It will fight any mob that has aggroed you. There’s no way to disable this sadly.
